In [48]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [3]:
len(a[a < 0])

4

In [5]:
len(a[a > 0])

5

In [54]:
b = [a > 0]
c = a[tuple(b)]
d = [c % 2 == 0]
len(c[tuple(d)])

3

In [12]:
plus_three = a + 3
len(plus_three[plus_three > 0])


10

In [14]:
a_sq = a**2
print(a_sq.mean())
print(a_sq.std())

74.0
144.0243035046516


In [18]:
mn = a.mean()
cent_a = a - mn
print(cent_a)
print(cent_a.mean())

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]
0.0


In [19]:
st_d = a.std()
mn = a.mean()
alter1 = a - mn
z = alter1 / st_d
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [23]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array(a)
sum_of_a = a.sum()
sum_of_a

55

In [24]:
min_of_a = a.min()
min_of_a

1

In [25]:
max_of_a = a.max()
max_of_a

10

In [26]:
mean_of_a = a.mean()
mean_of_a

5.5

In [28]:
product_of_a = a.prod()
product_of_a

3628800

In [30]:
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [32]:
odds_in_a = np.extract(a % 2 != 0, a)
odds_in_a

array([1, 3, 5, 7, 9])

In [33]:
evens_in_a = np.extract(a % 2 == 0, a)
evens_in_a

array([ 2,  4,  6,  8, 10])

In [34]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [35]:
sum(a)

55

In [36]:
min(a)

1

In [37]:
max(a)

10

In [38]:
sum(a)/len(a)

5.5

In [39]:
c = 1
for x in a:
    c = x * c
print(c)
    

3628800


In [41]:
temp = []
for x in a:
    temp.append(x**2)
print(temp)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [42]:
temp = []
for x in a:
    if x % 2 != 0:
        temp.append(x)
print(temp)

[1, 3, 5, 7, 9]


In [43]:
temp = []
for x in a:
    if x % 2 == 0:
        temp.append(x)
print(temp)

[2, 4, 6, 8, 10]


In [55]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [62]:
b = np.array(b)
sum_of_b = np.sum(b)
sum_of_b

33

In [63]:
min_of_b = np.min(b)
min_of_b

3

In [64]:
max_of_b = np.max(b)
max_of_b

8

In [65]:
mean_of_b = np.mean(b)
mean_of_b

5.5

In [67]:
product_of_b = np.prod(b)
product_of_b

20160

In [69]:
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [70]:
odds_in_b = np.extract(b % 2 != 0, b)
odds_in_b

array([3, 5, 7])

In [71]:
evens_in_b = np.extract(b % 2 == 0, b)
evens_in_b

array([4, 6, 8])

In [73]:
shape_of_b = np.shape(b)
shape_of_b

(2, 3)

In [74]:
trans_of_b = np.transpose(b)
trans_of_b

array([[3, 6],
       [4, 7],
       [5, 8]])

In [93]:
resh_of_b = np.reshape(b, (1, 6))
resh_of_b = resh_of_b.tolist()
resh_of_b

[[3, 4, 5, 6, 7, 8]]

In [91]:
resh_of_b2 = np.reshape(b, (6, 1))
resh_of_b2 = resh_of_b2.tolist()
resh_of_b2

[[3], [4], [5], [6], [7], [8]]

In [94]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
np.array(c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
print(np.min(c))
print(np.max(c))
print(np.sum(c))
print(np.prod(c))

1
9
45
362880


In [97]:
print(np.std(c))

2.581988897471611


In [98]:
print(np.var(c))

6.666666666666667


In [99]:
print(np.shape(c))

(3, 3)


In [100]:
print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [101]:
print(np.dot(c, c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [103]:
print(np.sum(c * np.transpose(c)))

261


In [104]:
print(np.prod(c * np.transpose(c)))

131681894400


In [125]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)

In [126]:
print(np.sin(d))

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


In [127]:
print(np.cos(d))

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


In [128]:
print(np.tan(d))

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


In [131]:
negat_in_d = np.extract(d < 0, d)
negat_in_d

array([-90, -30, -45, -45])

In [132]:
pos_in_d = np.extract(d > 0, d)
pos_in_d

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [133]:
uni_in_d = np.unique(d)
uni_in_d

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [134]:
uni_in_d = np.unique(d)
len(uni_in_d)

11

In [135]:
np.shape(d)

(3, 6)

In [136]:
np.transpose(d)

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [137]:
np.reshape(d, (9, 2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])